#Obstacle marking parameters
obstacle_range: 2.5
min_obstacle_height: -0.08
max_obstacle_height: 4.0
raytrace_range: 3.0

#Robot's footprint
footprint: [[-0.28, -0.3], [-0.28, 0.3], [0.28, 0.3],[0.28, -0.3]]
footprint_padding: 0.05

#Cost function parameters
inflation_radius: 0.55
cost_scaling_factor: 10.0

#Cost
lethal_cost_threshold: 100

observation_sources: laser_scan_sensor 

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}

#Obstacle marking parameters
obstacle_range: 2.5
min_obstacle_height: -0.08
max_obstacle_height: 4.0
raytrace_range: 3.0

#Robot's footprint
footprint: [[-0.28, -0.3], [-0.28, 0.3], [0.28, 0.3],[0.28, -0.3]]
footprint_padding: 0.05

#Cost function parameters
inflation_radius: 0.55
cost_scaling_factor: 10.0

#Cost
lethal_cost_threshold: 100

observation_sources: laser_scan_sensor 

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}

